; inc and dec are used for these two procedures.
; use substitution to illustrate the process generated by each procedure
; in evaluating (+ 4 5). Are these processes iterative or recursive?
; note: both are 'recursive procedures', only one seems to be a 'recursive process'
; note2: note is correct.
;
; by the way.. these don't run, dec isn't defined!


(define (+ a b)
  (if (= a 0)
    b
    (inc (+ (dec a) b))))
; recursive... inc is stored in each layer of the procedure:
; (+ 4 5)
; (inc (+ 3 5))
; (inc (inc (+ 2 5)))
; (inc (inc (inc (+ 1 5))))
; (inc (inc (inc (inc (+ 0 5)))))
; (inc (inc (inc (inc 5))))
; (inc (inc (inc 6)))
; (inc (inc 7))
; (inc 8)
; 9


(define (+ a b)
  (if (= a 0)
    b
    (+ (dec a) (inc b))))
; iterative... dec and inc are performed in place each time, all info stored in state.
; (+ 4 5)
; (+ 3 6)
; (+ 2 7)
; (+ 1 8)
; (+ 0 9)
; 9
